Remove use of pylab.hold
pylab.hold(True) has always been the default, has been deprecated
since matplotlib 2.1 and was removed in 3.0, yielding

  AttributeError: module 'matplotlib.pylab' has no attribute 'hold'

Instead of pylab.hold(False), one should create a new
figure (automatic in some environments, such as in a new Jupyter
cell).  Further discussion:

  https://github.com/matplotlib/matplotlib/issues/12337/